apiVersion: apiextensions.k8s.io/v1
kind: "CustomResourceDefinition"
metadata:
    name: "grantedaccess.backups.riotkit.org"
spec:
    group: "backups.riotkit.org"
    scope: "Namespaced"
    names:
        plural: "grantedaccess"
        singular: "grantedaccess"
        kind: "GrantedAccess"
        shortNames:
            - "gaccess"
            - "brjwts"
    versions:
        - name: v1alpha1
          served: true
          storage: true

          schema:
              openAPIV3Schema:
                  type: object
                  required: ["spec"]
                  properties:
                      spec:
                          type: object
                          required: ["expiresAt", "active", "description", "requesterIP"]
                          properties:
                              expiresAt:
                                  type: "string"
                              active:
                                  type: "boolean"
                              description:
                                  type: "string"
                              requesterIP:
                                  type: "string"
          additionalPrinterColumns:
            - name: Expiration
              type: string
              jsonPath: .spec.expiresAt

            - name: Is active
              type: boolean
              jsonPath: .spec.active

            - name: Requester
              type: string
              jsonPath: .spec.requesterIP
