---
apiVersion: backups.riotkit.org/v1alpha1
kind: BackupCollection
metadata:
    name: iwa-ait
spec:
    description: IWA-AIT website files
    filenameTemplate: iwa-ait-${version}.tar.gz
    maxBackupsCount: 5
    maxOneVersionSize: 1M
    maxCollectionSize: 10M

    # optional
    window:
        - from: "00 30 * * *"
          duration: 1h

    # fifo, fifo-plus-older
    strategyName: fifo
    strategySpec:
        keepLastOlderNotMoreThan: 5d
        maxOlderCopies: 2

    accessControl:
        - userName: admin
          roles:
              - collectionManager
